version: "3"

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongouser
      MONGO_INITDB_DATABASE: orderdb
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb-data:

